package snapshot_test

// Reading a snapshotted file back, against the hash the snapshot recorded.
//
// Extracted during the eval slice from a copy in `profile`, and now relied on
// by `eval` as well. The guarantee is narrow and load-bearing: a consumer that
// measures prose must be measuring the bytes the snapshot attested to, or every
// provenance stamp on the result is a lie.

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/fissible/hapax/internal/identity"
	"github.com/fissible/hapax/internal/snapshot"
	"github.com/fissible/hapax/internal/text"
)

func writeFile(t *testing.T, body string) (root, name string) {
	t.Helper()
	root = t.TempDir()
	name = "doc.md"
	if err := os.WriteFile(filepath.Join(root, name), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	return root, name
}

// The hash is over ADMITTED bytes, not the bytes on disk. Admission strips a
// BOM, so a file that differs only by its BOM verifies against the same hash —
// and a consumer hashing the raw file instead would reject a document the
// corpus admitted.
func TestVerificationIsAgainstAdmittedBytes(t *testing.T) {
	const body = "Some prose that stands in for a document.\n"

	admitted, err := text.Admit([]byte(body))
	if err != nil {
		t.Fatal(err)
	}
	hash := identity.HashBytes(admitted.Raw())

	for name, stored := range map[string]string{
		"as written": body,
		"with a BOM": string([]byte{0xEF, 0xBB, 0xBF}) + body,
	} {
		t.Run(name, func(t *testing.T) {
			root, file := writeFile(t, stored)
			doc, err := snapshot.ReadVerified(root, file, hash)
			if err != nil {
				t.Fatalf("ReadVerified: %v", err)
			}
			if got := string(doc.Raw()); got != body {
				t.Errorf("admitted bytes = %q, want %q", got, body)
			}
		})
	}
}

func TestVerificationRefuses(t *testing.T) {
	const body = "Some prose that stands in for a document.\n"
	admitted, err := text.Admit([]byte(body))
	if err != nil {
		t.Fatal(err)
	}
	hash := identity.HashBytes(admitted.Raw())

	t.Run("content changed", func(t *testing.T) {
		root, file := writeFile(t, "Different prose of the very same length!!\n")
		if _, err := snapshot.ReadVerified(root, file, hash); err == nil {
			t.Error("a changed document verified against the old hash")
		}
	})

	t.Run("one byte changed", func(t *testing.T) {
		root, file := writeFile(t, "Some prose that stands in for a document,\n")
		if _, err := snapshot.ReadVerified(root, file, hash); err == nil {
			t.Error("a one-character change verified")
		}
	})

	t.Run("missing file", func(t *testing.T) {
		root, _ := writeFile(t, body)
		if _, err := snapshot.ReadVerified(root, "absent.md", hash); err == nil {
			t.Error("a missing document verified")
		}
	})

	t.Run("not admissible", func(t *testing.T) {
		root := t.TempDir()
		if err := os.WriteFile(filepath.Join(root, "bad.md"), []byte{0xff, 0xfe, 0xfd}, 0o644); err != nil {
			t.Fatal(err)
		}
		if _, err := snapshot.ReadVerified(root, "bad.md", hash); err == nil {
			t.Error("invalid UTF-8 verified")
		}
	})

	// An empty expected hash must not act as a wildcard.
	t.Run("empty expected hash", func(t *testing.T) {
		root, file := writeFile(t, body)
		if _, err := snapshot.ReadVerified(root, file, ""); err == nil {
			t.Error("an empty expected hash accepted the document")
		}
	})
}

// A path that climbs out of the root is refused. The reviewer pointed out that
// the previous comment here claimed containment while the code only resolved
// nested paths, and that ReadVerified is now a shared exported helper rather
// than an internal detail of `profile`. Snapshot paths are machine-generated by
// corpus.Walk today, so this is not an attack surface — but a helper whose
// comment promises containment must provide it.
//
// Symlinks that point outside the root are NOT covered and containment is not
// claimed against them; that would need resolution against the real path and is
// its own decision.
func TestPathsThatEscapeTheRootAreRefused(t *testing.T) {
	const body = "Prose that lives outside the corpus root entirely.\n"
	parent := t.TempDir()
	root := filepath.Join(parent, "corpus")
	if err := os.MkdirAll(root, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(parent, "outside.md"), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	admitted, err := text.Admit([]byte(body))
	if err != nil {
		t.Fatal(err)
	}
	hash := identity.HashBytes(admitted.Raw())

	for _, path := range []string{
		"../outside.md",
		"nested/../../outside.md",
		"./../outside.md",
	} {
		t.Run(path, func(t *testing.T) {
			if _, err := snapshot.ReadVerified(root, path, hash); err == nil {
				t.Errorf("a path escaping the root was read: %q", path)
			}
		})
	}
}

// Paths are slash-separated in a snapshot and must resolve under the root on
// any platform.
func TestNestedSlashPathsResolve(t *testing.T) {
	const body = "Prose in a nested directory of the corpus.\n"
	root := t.TempDir()
	if err := os.MkdirAll(filepath.Join(root, "essays", "2026"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "essays", "2026", "a.md"), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	admitted, err := text.Admit([]byte(body))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := snapshot.ReadVerified(root, "essays/2026/a.md", identity.HashBytes(admitted.Raw())); err != nil {
		t.Fatalf("ReadVerified on a nested slash path: %v", err)
	}
}
