package store

// The checks are intentionally explicit. Apart from preventing malformed data,
// their names make the persistence allowlist auditable in sqlite_master.
var migrations = []string{`
CREATE TABLE migration (version INTEGER NOT NULL PRIMARY KEY CHECK(version >= 0), checksum TEXT NOT NULL CHECK(length(checksum)=64 AND checksum NOT GLOB '*[^0-9a-f]*'), applied_at TEXT NOT NULL CHECK(strftime('%Y-%m-%dT%H:%M:%SZ',applied_at) IS NOT NULL AND strftime('%Y-%m-%dT%H:%M:%SZ',applied_at)=applied_at));
CREATE TABLE snapshot (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), policy_digest TEXT NOT NULL CHECK(length(policy_digest)=64 AND policy_digest NOT GLOB '*[^0-9a-f]*'), created_at TEXT NOT NULL CHECK(strftime('%Y-%m-%dT%H:%M:%SZ',created_at) IS NOT NULL AND strftime('%Y-%m-%dT%H:%M:%SZ',created_at)=created_at));
CREATE TABLE document (document_id TEXT NOT NULL PRIMARY KEY CHECK(length(document_id)=64 AND document_id NOT GLOB '*[^0-9a-f]*'), snapshot_id TEXT NOT NULL CHECK(length(snapshot_id)=64 AND snapshot_id NOT GLOB '*[^0-9a-f]*') REFERENCES snapshot(id) ON DELETE CASCADE, path TEXT NOT NULL CHECK(path <> '' AND path NOT GLOB '/*' AND path NOT GLOB '*\*' AND path NOT GLOB '../*' AND path <> '..' AND path NOT GLOB '*//*'), content_hash TEXT NOT NULL CHECK(length(content_hash)=64 AND content_hash NOT GLOB '*[^0-9a-f]*'), register TEXT NOT NULL CHECK(register GLOB '[a-z0-9]*' AND register NOT GLOB '*[^a-z0-9-]*' AND length(register)<=32), split TEXT NOT NULL CHECK(split IN ('train','calibrate','test','draft')), admission TEXT NOT NULL CHECK(admission IN ('eligible','rejected-too-short','rejected-not-utf8','rejected-duplicate')), language TEXT NOT NULL CHECK(length(language) BETWEEN 2 AND 35 AND language NOT GLOB '*[^a-z0-9-]*'), unavailable_at TEXT CHECK(unavailable_at IS NULL OR (strftime('%Y-%m-%dT%H:%M:%SZ',unavailable_at) IS NOT NULL AND strftime('%Y-%m-%dT%H:%M:%SZ',unavailable_at)=unavailable_at)));
CREATE TABLE node (node_id TEXT NOT NULL PRIMARY KEY CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*'), document_id TEXT NOT NULL CHECK(length(document_id)=64 AND document_id NOT GLOB '*[^0-9a-f]*') REFERENCES document(document_id) ON DELETE CASCADE, ordinal INTEGER NOT NULL CHECK(ordinal>=0), kind TEXT NOT NULL CHECK(kind IN ('container','leaf')), role TEXT NOT NULL CHECK(role IN ('paragraph','heading','code-block','front-matter','table-cell','footnote','caption','image','html-block','definition-term','definition-description')), containers TEXT NOT NULL CHECK(containers='' OR (containers NOT GLOB '*[^a-z-]*' AND containers NOT GLOB '*||*' AND containers NOT GLOB '|*' AND containers NOT GLOB '*|')), offset INTEGER NOT NULL CHECK(offset>=0), length INTEGER NOT NULL CHECK(length>0), included INTEGER NOT NULL CHECK(included IN (0,1)), exclusion TEXT NOT NULL CHECK(exclusion IN ('','excluded-by-role','excluded-not-sentential','excluded-by-block-quote-policy')));
CREATE TABLE feature_vector (node_id TEXT NOT NULL CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*'), manifest_digest TEXT NOT NULL CHECK(length(manifest_digest)=64 AND manifest_digest NOT GLOB '*[^0-9a-f]*'), set_version INTEGER NOT NULL CHECK(set_version>=0), tokens INTEGER NOT NULL CHECK(tokens>=0), lexical_tokens INTEGER NOT NULL CHECK(lexical_tokens>=0), PRIMARY KEY(node_id,manifest_digest), FOREIGN KEY(node_id) REFERENCES node(node_id) ON DELETE CASCADE);
CREATE TABLE feature_value (node_id TEXT NOT NULL CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*'), manifest_digest TEXT NOT NULL CHECK(length(manifest_digest)=64 AND manifest_digest NOT GLOB '*[^0-9a-f]*'), feature TEXT NOT NULL CHECK(feature GLOB '[a-z]*' AND feature NOT GLOB '*[^a-z0-9_]*'), value REAL NOT NULL, defined INTEGER NOT NULL CHECK(defined IN (0,1)), sampling_variance REAL NOT NULL, sampling_variance_defined INTEGER NOT NULL CHECK(sampling_variance_defined IN (0,1)), PRIMARY KEY(node_id,manifest_digest,feature), FOREIGN KEY(node_id,manifest_digest) REFERENCES feature_vector(node_id,manifest_digest) ON DELETE CASCADE);
CREATE TABLE profile (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), snapshot_id TEXT NOT NULL CHECK(length(snapshot_id)=64 AND snapshot_id NOT GLOB '*[^0-9a-f]*') REFERENCES snapshot(id) ON DELETE CASCADE, register TEXT NOT NULL CHECK(register GLOB '[a-z0-9]*' AND register NOT GLOB '*[^a-z0-9-]*' AND length(register)<=32), unit TEXT NOT NULL CHECK(unit IN ('document','paragraph')), variance_convention TEXT NOT NULL CHECK(variance_convention IN ('sample')), manifest_digest TEXT NOT NULL CHECK(length(manifest_digest)=64 AND manifest_digest NOT GLOB '*[^0-9a-f]*'), feature_set_version INTEGER NOT NULL CHECK(feature_set_version>=0), min_paragraph_lexical_tokens INTEGER NOT NULL CHECK(min_paragraph_lexical_tokens>=0));
CREATE TABLE profile_stat (profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, feature TEXT NOT NULL CHECK(feature GLOB '[a-z]*' AND feature NOT GLOB '*[^a-z0-9_]*'), n INTEGER NOT NULL CHECK(n>=0), mean REAL NOT NULL, variance REAL NOT NULL, defined INTEGER NOT NULL CHECK(defined IN (0,1)), variance_defined INTEGER NOT NULL CHECK(variance_defined IN (0,1)), min_observations INTEGER NOT NULL CHECK(min_observations>=0), PRIMARY KEY(profile_id,feature));
CREATE TABLE profile_head (register TEXT NOT NULL PRIMARY KEY CHECK(register GLOB '[a-z0-9]*' AND register NOT GLOB '*[^a-z0-9-]*' AND length(register)<=32), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, updated_at TEXT NOT NULL CHECK(strftime('%Y-%m-%dT%H:%M:%SZ',updated_at) IS NOT NULL AND strftime('%Y-%m-%dT%H:%M:%SZ',updated_at)=updated_at));
CREATE TABLE reference (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, split TEXT NOT NULL CHECK(split IN ('train','calibrate','test','draft')), min_segments INTEGER NOT NULL CHECK(min_segments>=0), manifest_digest TEXT NOT NULL CHECK(length(manifest_digest)=64 AND manifest_digest NOT GLOB '*[^0-9a-f]*'));
CREATE TABLE reference_value (reference_id TEXT NOT NULL CHECK(length(reference_id)=64 AND reference_id NOT GLOB '*[^0-9a-f]*') REFERENCES reference(id) ON DELETE CASCADE, feature TEXT NOT NULL CHECK(feature GLOB '[a-z]*' AND feature NOT GLOB '*[^a-z0-9_]*'), ordinal INTEGER NOT NULL CHECK(ordinal>=0), value REAL NOT NULL, PRIMARY KEY(reference_id,feature,ordinal));
CREATE TABLE threshold (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, reference_id TEXT NOT NULL CHECK(length(reference_id)=64 AND reference_id NOT GLOB '*[^0-9a-f]*') REFERENCES reference(id) ON DELETE CASCADE, population_id TEXT NOT NULL CHECK(length(population_id)=64 AND population_id NOT GLOB '*[^0-9a-f]*'), t_low REAL NOT NULL, t_high REAL NOT NULL, achieved_author REAL NOT NULL, achieved_distractor REAL NOT NULL, interval_low_lower REAL NOT NULL, interval_low_upper REAL NOT NULL, interval_high_lower REAL NOT NULL, interval_high_upper REAL NOT NULL, verdict TEXT NOT NULL CHECK(verdict IN ('separated','pair-incompatible')) CHECK((verdict='separated')=(t_low<t_high)) CHECK(interval_low_lower<=interval_low_upper) CHECK(interval_high_lower<=interval_high_upper));
CREATE TABLE eval_result (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, reference_id TEXT NOT NULL CHECK(length(reference_id)=64 AND reference_id NOT GLOB '*[^0-9a-f]*') REFERENCES reference(id) ON DELETE CASCADE, auc REAL NOT NULL, lower_bound REAL NOT NULL, cap REAL NOT NULL, author_segments INTEGER NOT NULL CHECK(author_segments>=0), distractor_segments INTEGER NOT NULL CHECK(distractor_segments>=0), author_clusters INTEGER NOT NULL CHECK(author_clusters>=0), distractor_clusters INTEGER NOT NULL CHECK(distractor_clusters>=0), discriminates INTEGER NOT NULL CHECK(discriminates IN (0,1)), calibrated INTEGER NOT NULL CHECK(calibrated IN (0,1)), shippable INTEGER NOT NULL CHECK(shippable IN (0,1)) CHECK(shippable=(discriminates AND calibrated)), reason TEXT NOT NULL CHECK(reason IN ('','discrimination-failed','uncalibrated')) CHECK((shippable=1)=(reason='')));
CREATE TABLE exemplar_selection (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, n INTEGER NOT NULL CHECK(n>=0), certificate_id TEXT NOT NULL CHECK(length(certificate_id)=64 AND certificate_id NOT GLOB '*[^0-9a-f]*'));
CREATE TABLE exemplar_member (selection_id TEXT NOT NULL CHECK(length(selection_id)=64 AND selection_id NOT GLOB '*[^0-9a-f]*') REFERENCES exemplar_selection(id) ON DELETE CASCADE, ordinal INTEGER NOT NULL CHECK(ordinal>=0), node_id TEXT NOT NULL CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*') REFERENCES node(node_id) ON DELETE CASCADE, PRIMARY KEY(selection_id,ordinal));
CREATE TABLE rewrite_attempt (invocation_id TEXT NOT NULL CHECK(length(invocation_id)=64 AND invocation_id NOT GLOB '*[^0-9a-f]*'), attempt_index INTEGER NOT NULL CHECK(attempt_index>=0), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, provider_id TEXT NOT NULL CHECK(provider_id IN ('ollama','anthropic')), node_id TEXT NOT NULL CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*') REFERENCES node(node_id) ON DELETE CASCADE, current_hash TEXT NOT NULL CHECK(length(current_hash)=64 AND current_hash NOT GLOB '*[^0-9a-f]*'), candidate_hash TEXT NOT NULL CHECK(length(candidate_hash)=64 AND candidate_hash NOT GLOB '*[^0-9a-f]*'), current_distance REAL NOT NULL, candidate_distance REAL NOT NULL, current_band TEXT NOT NULL CHECK(current_band IN ('','in-range','drifting','not-you')), candidate_band TEXT NOT NULL CHECK(candidate_band IN ('','in-range','drifting','not-you')), preserved INTEGER NOT NULL CHECK(preserved IN (0,1)), tells_comparison INTEGER NOT NULL, tells_comparable INTEGER NOT NULL CHECK(tells_comparable IN (0,1)), accepted INTEGER NOT NULL CHECK(accepted IN (0,1)), rejection TEXT NOT NULL CHECK(rejection IN ('','not-one-segment','unscoreable','candidate-unscoreable','uncalibrated','different-features','not-preserved','tells-incomparable','tells-worse','not-improved')) CHECK((accepted=1)=(rejection='')) CHECK(accepted=0 OR (current_band<>'' AND candidate_band<>'')), PRIMARY KEY(invocation_id,attempt_index));
CREATE TABLE rewrite_attempt_identifier (invocation_id TEXT NOT NULL CHECK(length(invocation_id)=64 AND invocation_id NOT GLOB '*[^0-9a-f]*'), attempt_index INTEGER NOT NULL CHECK(attempt_index>=0), ordinal INTEGER NOT NULL CHECK(ordinal>=0), identifier TEXT NOT NULL CHECK(identifier GLOB 'preserve-v1:*:*:????????????????' AND identifier NOT GLOB '*[^a-z0-9:-]*'), PRIMARY KEY(invocation_id,attempt_index,ordinal), FOREIGN KEY(invocation_id,attempt_index) REFERENCES rewrite_attempt(invocation_id,attempt_index) ON DELETE CASCADE);
`, `
DROP TABLE eval_result;
CREATE TABLE eval_result (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, reference_id TEXT NOT NULL CHECK(length(reference_id)=64 AND reference_id NOT GLOB '*[^0-9a-f]*') REFERENCES reference(id) ON DELETE CASCADE,
 discrimination_id TEXT NOT NULL CHECK(length(discrimination_id)=64 AND discrimination_id NOT GLOB '*[^0-9a-f]*'), discrimination_population_id TEXT NOT NULL CHECK(length(discrimination_population_id)=64 AND discrimination_population_id NOT GLOB '*[^0-9a-f]*'), discrimination_manifest_digest TEXT NOT NULL CHECK(length(discrimination_manifest_digest)=64 AND discrimination_manifest_digest NOT GLOB '*[^0-9a-f]*'), discrimination_weight_scheme TEXT NOT NULL CHECK(discrimination_weight_scheme GLOB '[a-z0-9]*' AND discrimination_weight_scheme NOT GLOB '*[^a-z0-9-]*'), discrimination_distance_algorithm TEXT NOT NULL CHECK(discrimination_distance_algorithm GLOB '[a-z0-9]*' AND discrimination_distance_algorithm NOT GLOB '*[^a-z0-9-]*'), discrimination_scored_tiers TEXT NOT NULL CHECK(discrimination_scored_tiers IN ('','A')), discrimination_split TEXT NOT NULL CHECK(discrimination_split IN ('train','calibrate','test','draft')), discrimination_algorithm TEXT NOT NULL CHECK(discrimination_algorithm GLOB '[a-z0-9]*' AND discrimination_algorithm NOT GLOB '*[^a-z0-9-]*'), discrimination_clustering TEXT NOT NULL CHECK(discrimination_clustering IN ('document')), discrimination_floor REAL NOT NULL CHECK(discrimination_floor>0 AND discrimination_floor<=1), discrimination_confidence REAL NOT NULL CHECK(discrimination_confidence>0 AND discrimination_confidence<1), discrimination_resamples INTEGER NOT NULL CHECK(discrimination_resamples>0), discrimination_seed INTEGER NOT NULL CHECK(discrimination_seed>=0), auc REAL NOT NULL, lower_bound REAL NOT NULL, cap REAL NOT NULL, author_segments INTEGER NOT NULL CHECK(author_segments>=0), distractor_segments INTEGER NOT NULL CHECK(distractor_segments>=0), author_clusters INTEGER NOT NULL CHECK(author_clusters>=0), distractor_clusters INTEGER NOT NULL CHECK(distractor_clusters>=0), min_clusters INTEGER NOT NULL CHECK(min_clusters>=0), discriminates INTEGER NOT NULL CHECK(discriminates IN (0,1)), discrimination_reason TEXT NOT NULL CHECK(discrimination_reason IN ('','lower-bound-below-floor')),
 calibration_id TEXT NOT NULL CHECK(length(calibration_id)=64 AND calibration_id NOT GLOB '*[^0-9a-f]*'), calibration_thresholds_id TEXT NOT NULL CHECK(length(calibration_thresholds_id)=64 AND calibration_thresholds_id NOT GLOB '*[^0-9a-f]*'), calibration_population_id TEXT NOT NULL CHECK(length(calibration_population_id)=64 AND calibration_population_id NOT GLOB '*[^0-9a-f]*'), calibration_manifest_digest TEXT NOT NULL CHECK(length(calibration_manifest_digest)=64 AND calibration_manifest_digest NOT GLOB '*[^0-9a-f]*'), calibration_weight_scheme TEXT NOT NULL CHECK(calibration_weight_scheme GLOB '[a-z0-9]*' AND calibration_weight_scheme NOT GLOB '*[^a-z0-9-]*'), calibration_distance_algorithm TEXT NOT NULL CHECK(calibration_distance_algorithm GLOB '[a-z0-9]*' AND calibration_distance_algorithm NOT GLOB '*[^a-z0-9-]*'), calibration_scored_tiers TEXT NOT NULL CHECK(calibration_scored_tiers IN ('','A')), calibration_split TEXT NOT NULL CHECK(calibration_split IN ('train','calibrate','test','draft')), calibration_algorithm TEXT NOT NULL CHECK(calibration_algorithm GLOB '[a-z0-9]*' AND calibration_algorithm NOT GLOB '*[^a-z0-9-]*'), calibration_low REAL NOT NULL, calibration_high REAL NOT NULL, calibration_confidence REAL NOT NULL CHECK(calibration_confidence>0 AND calibration_confidence<1), calibration_resamples INTEGER NOT NULL CHECK(calibration_resamples>0), calibration_seed INTEGER NOT NULL CHECK(calibration_seed>=0), calibrated INTEGER NOT NULL CHECK(calibrated IN (0,1)), calibration_reason TEXT NOT NULL CHECK(calibration_reason IN ('','no-claiming-band-emitted')), shippable INTEGER NOT NULL CHECK(shippable IN (0,1)), reason TEXT NOT NULL CHECK(reason IN ('','discrimination-failed','uncalibrated')) CHECK(shippable=(discriminates AND calibrated)) CHECK((shippable=1)=(reason='')));
CREATE TABLE calibration_band (eval_result_id TEXT NOT NULL CHECK(length(eval_result_id)=64 AND eval_result_id NOT GLOB '*[^0-9a-f]*') REFERENCES eval_result(id) ON DELETE CASCADE, band TEXT NOT NULL CHECK(band IN ('in-range','drifting','not-you')), claims TEXT NOT NULL CHECK(claims IN ('','author','distractor')), target REAL NOT NULL, error_rate REAL NOT NULL, error_bound REAL NOT NULL, class_segments INTEGER NOT NULL CHECK(class_segments>=0), class_clusters INTEGER NOT NULL CHECK(class_clusters>=0), min_class_clusters INTEGER NOT NULL CHECK(min_class_clusters>=0), author_segments INTEGER NOT NULL CHECK(author_segments>=0), distractor_segments INTEGER NOT NULL CHECK(distractor_segments>=0), emitted INTEGER NOT NULL CHECK(emitted IN (0,1)), reason TEXT NOT NULL CHECK(reason IN ('','empty-error-class','error-bound-exceeds-target')) CHECK((emitted=1)=(reason='')), PRIMARY KEY(eval_result_id, band));
CREATE TABLE release_head (profile_id TEXT NOT NULL PRIMARY KEY CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, eval_result_id TEXT NOT NULL CHECK(length(eval_result_id)=64 AND eval_result_id NOT GLOB '*[^0-9a-f]*') REFERENCES eval_result(id) ON DELETE CASCADE, updated_at TEXT NOT NULL CHECK(strftime('%Y-%m-%dT%H:%M:%SZ',updated_at) IS NOT NULL AND strftime('%Y-%m-%dT%H:%M:%SZ',updated_at)=updated_at));
`, `
ALTER TABLE document DROP COLUMN language;
ALTER TABLE document ADD COLUMN language TEXT NOT NULL DEFAULT 'not-performed' CHECK(language IN ('not-performed','passed','failed','skipped-by-policy'));
ALTER TABLE profile ADD COLUMN production_ready INTEGER NOT NULL DEFAULT 0 CHECK(production_ready IN (0,1));
ALTER TABLE profile ADD COLUMN not_ready_reason TEXT NOT NULL DEFAULT 'profile minimums are declared, not derived' CHECK(not_ready_reason IN ('','profile minimums are declared, not derived')) CHECK(production_ready=(not_ready_reason=''));
`, `
CREATE TABLE distractor_pool (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), policy_digest TEXT NOT NULL CHECK(length(policy_digest)=64 AND policy_digest NOT GLOB '*[^0-9a-f]*'), members INTEGER NOT NULL CHECK(members>=0), created_at TEXT NOT NULL CHECK(strftime('%Y-%m-%dT%H:%M:%SZ',created_at) IS NOT NULL AND strftime('%Y-%m-%dT%H:%M:%SZ',created_at)=created_at));
CREATE TABLE distractor_pool_member (pool_id TEXT NOT NULL CHECK(length(pool_id)=64 AND pool_id NOT GLOB '*[^0-9a-f]*') REFERENCES distractor_pool(id) ON DELETE CASCADE, content_hash TEXT NOT NULL CHECK(length(content_hash)=64 AND content_hash NOT GLOB '*[^0-9a-f]*'), PRIMARY KEY(pool_id,content_hash));
ALTER TABLE eval_result ADD COLUMN distractor_pool_id TEXT CHECK(distractor_pool_id IS NULL OR (length(distractor_pool_id)=64 AND distractor_pool_id NOT GLOB '*[^0-9a-f]*')) REFERENCES distractor_pool(id) ON DELETE RESTRICT;
`, `
CREATE TABLE rewrite_attempt_new (invocation_id TEXT NOT NULL CHECK(length(invocation_id)=64 AND invocation_id NOT GLOB '*[^0-9a-f]*'), attempt_index INTEGER NOT NULL CHECK(attempt_index>=0), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, provider_id TEXT NOT NULL CHECK(provider_id IN ('ollama','anthropic')), node_id TEXT NOT NULL CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*') REFERENCES node(node_id) ON DELETE CASCADE, current_hash TEXT NOT NULL CHECK(length(current_hash)=64 AND current_hash NOT GLOB '*[^0-9a-f]*'), candidate_hash TEXT NOT NULL CHECK(length(candidate_hash)=64 AND candidate_hash NOT GLOB '*[^0-9a-f]*'), current_distance REAL NOT NULL, candidate_distance REAL NOT NULL, current_band TEXT NOT NULL CHECK(current_band IN ('','in-range','drifting','not-you')), candidate_band TEXT NOT NULL CHECK(candidate_band IN ('','in-range','drifting','not-you')), preserved INTEGER NOT NULL CHECK(preserved IN (0,1)), tells_comparison INTEGER NOT NULL, tells_comparable INTEGER NOT NULL CHECK(tells_comparable IN (0,1)), accepted INTEGER NOT NULL CHECK(accepted IN (0,1)), rejection TEXT NOT NULL CHECK(rejection IN ('','not-one-segment','unscoreable','candidate-unscoreable','uncalibrated','different-features','not-preserved','tells-incomparable','tells-worse','not-improved')) CHECK((accepted=1)=(rejection='')) CHECK(accepted=0 OR (current_band<>'' AND candidate_band<>'')), PRIMARY KEY(invocation_id,node_id,attempt_index));
INSERT INTO rewrite_attempt_new SELECT invocation_id,attempt_index,profile_id,provider_id,node_id,current_hash,candidate_hash,current_distance,candidate_distance,current_band,candidate_band,preserved,tells_comparison,tells_comparable,accepted,rejection FROM rewrite_attempt;
CREATE TABLE rewrite_attempt_identifier_new (invocation_id TEXT NOT NULL CHECK(length(invocation_id)=64 AND invocation_id NOT GLOB '*[^0-9a-f]*'), node_id TEXT NOT NULL CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*'), attempt_index INTEGER NOT NULL CHECK(attempt_index>=0), ordinal INTEGER NOT NULL CHECK(ordinal>=0), identifier TEXT NOT NULL CHECK(identifier GLOB 'preserve-v1:*:*:????????????????' AND identifier NOT GLOB '*[^a-z0-9:-]*'), PRIMARY KEY(invocation_id,node_id,attempt_index,ordinal), FOREIGN KEY(invocation_id,node_id,attempt_index) REFERENCES rewrite_attempt_new(invocation_id,node_id,attempt_index) ON DELETE CASCADE);
INSERT INTO rewrite_attempt_identifier_new SELECT i.invocation_id,a.node_id,i.attempt_index,i.ordinal,i.identifier FROM rewrite_attempt_identifier AS i JOIN rewrite_attempt AS a ON a.invocation_id=i.invocation_id AND a.attempt_index=i.attempt_index;
DROP TABLE rewrite_attempt_identifier;
DROP TABLE rewrite_attempt;
ALTER TABLE rewrite_attempt_new RENAME TO rewrite_attempt;
ALTER TABLE rewrite_attempt_identifier_new RENAME TO rewrite_attempt_identifier;
`, `
CREATE TABLE node_new (node_id TEXT NOT NULL PRIMARY KEY CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*'), document_id TEXT NOT NULL CHECK(length(document_id)=64 AND document_id NOT GLOB '*[^0-9a-f]*') REFERENCES document(document_id) ON DELETE CASCADE, ordinal INTEGER NOT NULL CHECK(ordinal>=0), kind TEXT NOT NULL CHECK(kind IN ('container','leaf')), role TEXT NOT NULL CHECK(role IN ('paragraph','heading','code-block','front-matter','table-cell','footnote','caption','image','html-block','definition-term','definition-description')), containers TEXT NOT NULL CHECK(containers='' OR (containers NOT GLOB '*[^a-z|-]*' AND containers NOT GLOB '*||*' AND containers NOT GLOB '|*' AND containers NOT GLOB '*|')), offset INTEGER NOT NULL CHECK(offset>=0), length INTEGER NOT NULL CHECK(length>0), included INTEGER NOT NULL CHECK(included IN (0,1)), exclusion TEXT NOT NULL CHECK(exclusion IN ('','excluded-by-role','excluded-not-sentential','excluded-by-block-quote-policy')));
INSERT INTO node_new SELECT node_id,document_id,ordinal,kind,role,containers,offset,length,included,exclusion FROM node;
DROP TABLE node;
ALTER TABLE node_new RENAME TO node;
`, `
-- A split is a property of an ELIGIBLE document. A rejected one was never
-- assigned to train, calibrate or test, because it is not in any of them, and
-- the old constraint required a value it could never honestly carry.
--
-- The column now ADMITS the empty string; the pairing — eligible if and only if
-- a split is present — is enforced in Go rather than as a table CHECK, because a
-- table-level constraint referencing another column defeats the vocabulary
-- suite's ability to damage one column in isolation, and that suite is what
-- proves an out-of-vocabulary value is corrupt on read.
--
-- The effect was that hapax index failed outright on any corpus containing a
-- rejected document — too short, not UTF-8, or a near-duplicate. Every fixture
-- in this repository is generated and admits every file, so nothing caught it
-- until a real archive of resume revisions did: three revisions of one resume
-- are near-duplicates of each other, which is what a real archive looks like.
CREATE TABLE document_new (document_id TEXT NOT NULL PRIMARY KEY CHECK(length(document_id)=64 AND document_id NOT GLOB '*[^0-9a-f]*'), snapshot_id TEXT NOT NULL CHECK(length(snapshot_id)=64 AND snapshot_id NOT GLOB '*[^0-9a-f]*') REFERENCES snapshot(id) ON DELETE CASCADE, path TEXT NOT NULL CHECK(path <> '' AND path NOT GLOB '/*' AND path NOT GLOB '*\*' AND path NOT GLOB '../*' AND path <> '..' AND path NOT GLOB '*//*'), content_hash TEXT NOT NULL CHECK(length(content_hash)=64 AND content_hash NOT GLOB '*[^0-9a-f]*'), register TEXT NOT NULL CHECK(register GLOB '[a-z0-9]*' AND register NOT GLOB '*[^a-z0-9-]*' AND length(register)<=32), split TEXT NOT NULL CHECK(split IN ('train','calibrate','test','draft','')), admission TEXT NOT NULL CHECK(admission IN ('eligible','rejected-too-short','rejected-not-utf8','rejected-duplicate')), language TEXT NOT NULL DEFAULT 'not-performed' CHECK(language IN ('not-performed','passed','failed','skipped-by-policy')), unavailable_at TEXT CHECK(unavailable_at IS NULL OR (strftime('%Y-%m-%dT%H:%M:%SZ',unavailable_at) IS NOT NULL AND strftime('%Y-%m-%dT%H:%M:%SZ',unavailable_at)=unavailable_at)));
INSERT INTO document_new SELECT document_id,snapshot_id,path,content_hash,register,split,admission,language,unavailable_at FROM document;
DROP TABLE document;
ALTER TABLE document_new RENAME TO document;
`, `
CREATE TABLE rewrite_attempt_new (invocation_id TEXT NOT NULL CHECK(length(invocation_id)=64 AND invocation_id NOT GLOB '*[^0-9a-f]*'), attempt_index INTEGER NOT NULL CHECK(attempt_index>=0), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, provider_id TEXT NOT NULL CHECK(provider_id IN ('ollama','anthropic')), node_id TEXT NOT NULL CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*') REFERENCES node(node_id) ON DELETE CASCADE, current_hash TEXT NOT NULL CHECK(length(current_hash)=64 AND current_hash NOT GLOB '*[^0-9a-f]*'), candidate_hash TEXT NOT NULL CHECK(length(candidate_hash)=64 AND candidate_hash NOT GLOB '*[^0-9a-f]*'), current_distance REAL NOT NULL, candidate_distance REAL NOT NULL, current_band TEXT NOT NULL CHECK(current_band IN ('','in-range','drifting','not-you')), candidate_band TEXT NOT NULL CHECK(candidate_band IN ('','in-range','drifting','not-you')), preserved INTEGER NOT NULL CHECK(preserved IN (0,1)), tells_comparison INTEGER NOT NULL, tells_comparable INTEGER NOT NULL CHECK(tells_comparable IN (0,1)), accepted INTEGER NOT NULL CHECK(accepted IN (0,1)), rejection TEXT NOT NULL CHECK(rejection IN ('','not-one-segment','unscoreable','candidate-unscoreable','uncalibrated','different-features','not-preserved','tells-incomparable','tells-worse','not-improved')) CHECK((accepted=1)=(rejection='')) CHECK(accepted=0 OR (current_band<>'') = (candidate_band<>'')), PRIMARY KEY(invocation_id,node_id,attempt_index));
INSERT INTO rewrite_attempt_new SELECT invocation_id,attempt_index,profile_id,provider_id,node_id,current_hash,candidate_hash,current_distance,candidate_distance,current_band,candidate_band,preserved,tells_comparison,tells_comparable,accepted,rejection FROM rewrite_attempt;
CREATE TABLE rewrite_attempt_identifier_new (invocation_id TEXT NOT NULL CHECK(length(invocation_id)=64 AND invocation_id NOT GLOB '*[^0-9a-f]*'), node_id TEXT NOT NULL CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*'), attempt_index INTEGER NOT NULL CHECK(attempt_index>=0), ordinal INTEGER NOT NULL CHECK(ordinal>=0), identifier TEXT NOT NULL CHECK(identifier GLOB 'preserve-v1:*:*:????????????????' AND identifier NOT GLOB '*[^a-z0-9:-]*'), PRIMARY KEY(invocation_id,node_id,attempt_index,ordinal), FOREIGN KEY(invocation_id,node_id,attempt_index) REFERENCES rewrite_attempt_new(invocation_id,node_id,attempt_index) ON DELETE CASCADE);
INSERT INTO rewrite_attempt_identifier_new SELECT invocation_id,node_id,attempt_index,ordinal,identifier FROM rewrite_attempt_identifier;
DROP TABLE rewrite_attempt_identifier;
DROP TABLE rewrite_attempt;
ALTER TABLE rewrite_attempt_new RENAME TO rewrite_attempt;
ALTER TABLE rewrite_attempt_identifier_new RENAME TO rewrite_attempt_identifier;
`}
