package store

// The checks are intentionally explicit. Apart from preventing malformed data,
// their names make the persistence allowlist auditable in sqlite_master.
var migrations = []string{`
CREATE TABLE migration (version INTEGER NOT NULL PRIMARY KEY CHECK(version >= 0), checksum TEXT NOT NULL CHECK(length(checksum)=64 AND checksum NOT GLOB '*[^0-9a-f]*'), applied_at TEXT NOT NULL CHECK(strftime('%Y-%m-%dT%H:%M:%SZ',applied_at) IS NOT NULL AND strftime('%Y-%m-%dT%H:%M:%SZ',applied_at)=applied_at));
CREATE TABLE snapshot (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), policy_digest TEXT NOT NULL CHECK(length(policy_digest)=64 AND policy_digest NOT GLOB '*[^0-9a-f]*'), created_at TEXT NOT NULL CHECK(strftime('%Y-%m-%dT%H:%M:%SZ',created_at) IS NOT NULL AND strftime('%Y-%m-%dT%H:%M:%SZ',created_at)=created_at));
CREATE TABLE document (document_id TEXT NOT NULL PRIMARY KEY CHECK(length(document_id)=64 AND document_id NOT GLOB '*[^0-9a-f]*'), snapshot_id TEXT NOT NULL CHECK(length(snapshot_id)=64 AND snapshot_id NOT GLOB '*[^0-9a-f]*') REFERENCES snapshot(id) ON DELETE CASCADE, path TEXT NOT NULL CHECK(path <> '' AND path NOT GLOB '/*' AND path NOT GLOB '*\*' AND path NOT GLOB '../*' AND path <> '..' AND path NOT GLOB '*//*'), content_hash TEXT NOT NULL CHECK(length(content_hash)=64 AND content_hash NOT GLOB '*[^0-9a-f]*'), register TEXT NOT NULL CHECK(register GLOB '[a-z0-9]*' AND register NOT GLOB '*[^a-z0-9-]*' AND length(register)<=32), split TEXT NOT NULL CHECK(split IN ('train','calibrate','test','draft')), admission TEXT NOT NULL CHECK(admission IN ('eligible','rejected-too-short','rejected-not-utf8','rejected-duplicate')), language TEXT NOT NULL CHECK(length(language) BETWEEN 2 AND 35 AND language NOT GLOB '*[^a-z0-9-]*'), unavailable_at TEXT CHECK(unavailable_at IS NULL OR (strftime('%Y-%m-%dT%H:%M:%SZ',unavailable_at) IS NOT NULL AND strftime('%Y-%m-%dT%H:%M:%SZ',unavailable_at)=unavailable_at)));
CREATE TABLE node (node_id TEXT NOT NULL PRIMARY KEY CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*'), document_id TEXT NOT NULL CHECK(length(document_id)=64 AND document_id NOT GLOB '*[^0-9a-f]*') REFERENCES document(document_id) ON DELETE CASCADE, ordinal INTEGER NOT NULL CHECK(ordinal>=0), kind TEXT NOT NULL CHECK(kind IN ('container','leaf')), role TEXT NOT NULL CHECK(role IN ('paragraph','heading','code-block','front-matter','table-cell','footnote','caption','image','html-block','definition-term','definition-description')), containers TEXT NOT NULL CHECK(containers='' OR (containers NOT GLOB '*[^a-z-]*' AND containers NOT GLOB '*||*' AND containers NOT GLOB '|*' AND containers NOT GLOB '*|')), offset INTEGER NOT NULL CHECK(offset>=0), length INTEGER NOT NULL CHECK(length>0), included INTEGER NOT NULL CHECK(included IN (0,1)), exclusion TEXT NOT NULL CHECK(exclusion IN ('','excluded-by-role','excluded-not-sentential','excluded-by-block-quote-policy')));
CREATE TABLE feature_vector (node_id TEXT NOT NULL CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*'), manifest_digest TEXT NOT NULL CHECK(length(manifest_digest)=64 AND manifest_digest NOT GLOB '*[^0-9a-f]*'), set_version INTEGER NOT NULL CHECK(set_version>=0), tokens INTEGER NOT NULL CHECK(tokens>=0), lexical_tokens INTEGER NOT NULL CHECK(lexical_tokens>=0), PRIMARY KEY(node_id,manifest_digest), FOREIGN KEY(node_id) REFERENCES node(node_id) ON DELETE CASCADE);
CREATE TABLE feature_value (node_id TEXT NOT NULL CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*'), manifest_digest TEXT NOT NULL CHECK(length(manifest_digest)=64 AND manifest_digest NOT GLOB '*[^0-9a-f]*'), feature TEXT NOT NULL CHECK(feature GLOB '[a-z]*' AND feature NOT GLOB '*[^a-z0-9_]*'), value REAL NOT NULL, defined INTEGER NOT NULL CHECK(defined IN (0,1)), sampling_variance REAL NOT NULL, sampling_variance_defined INTEGER NOT NULL CHECK(sampling_variance_defined IN (0,1)), PRIMARY KEY(node_id,manifest_digest,feature), FOREIGN KEY(node_id,manifest_digest) REFERENCES feature_vector(node_id,manifest_digest) ON DELETE CASCADE);
CREATE TABLE profile (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), snapshot_id TEXT NOT NULL CHECK(length(snapshot_id)=64 AND snapshot_id NOT GLOB '*[^0-9a-f]*') REFERENCES snapshot(id) ON DELETE CASCADE, register TEXT NOT NULL CHECK(register GLOB '[a-z0-9]*' AND register NOT GLOB '*[^a-z0-9-]*' AND length(register)<=32), unit TEXT NOT NULL CHECK(unit IN ('document','paragraph')), variance_convention TEXT NOT NULL CHECK(variance_convention IN ('sample')), manifest_digest TEXT NOT NULL CHECK(length(manifest_digest)=64 AND manifest_digest NOT GLOB '*[^0-9a-f]*'), feature_set_version INTEGER NOT NULL CHECK(feature_set_version>=0), min_paragraph_lexical_tokens INTEGER NOT NULL CHECK(min_paragraph_lexical_tokens>=0));
CREATE TABLE profile_stat (profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, feature TEXT NOT NULL CHECK(feature GLOB '[a-z]*' AND feature NOT GLOB '*[^a-z0-9_]*'), n INTEGER NOT NULL CHECK(n>=0), mean REAL NOT NULL, variance REAL NOT NULL, defined INTEGER NOT NULL CHECK(defined IN (0,1)), variance_defined INTEGER NOT NULL CHECK(variance_defined IN (0,1)), min_observations INTEGER NOT NULL CHECK(min_observations>=0), PRIMARY KEY(profile_id,feature));
CREATE TABLE profile_head (register TEXT NOT NULL PRIMARY KEY CHECK(register GLOB '[a-z0-9]*' AND register NOT GLOB '*[^a-z0-9-]*' AND length(register)<=32), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, updated_at TEXT NOT NULL CHECK(strftime('%Y-%m-%dT%H:%M:%SZ',updated_at) IS NOT NULL AND strftime('%Y-%m-%dT%H:%M:%SZ',updated_at)=updated_at));
CREATE TABLE reference (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, split TEXT NOT NULL CHECK(split IN ('train','calibrate','test','draft')), min_segments INTEGER NOT NULL CHECK(min_segments>=0), manifest_digest TEXT NOT NULL CHECK(length(manifest_digest)=64 AND manifest_digest NOT GLOB '*[^0-9a-f]*'));
CREATE TABLE reference_value (reference_id TEXT NOT NULL CHECK(length(reference_id)=64 AND reference_id NOT GLOB '*[^0-9a-f]*') REFERENCES reference(id) ON DELETE CASCADE, feature TEXT NOT NULL CHECK(feature GLOB '[a-z]*' AND feature NOT GLOB '*[^a-z0-9_]*'), ordinal INTEGER NOT NULL CHECK(ordinal>=0), value REAL NOT NULL, PRIMARY KEY(reference_id,feature,ordinal));
CREATE TABLE threshold (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, reference_id TEXT NOT NULL CHECK(length(reference_id)=64 AND reference_id NOT GLOB '*[^0-9a-f]*') REFERENCES reference(id) ON DELETE CASCADE, population_id TEXT NOT NULL CHECK(length(population_id)=64 AND population_id NOT GLOB '*[^0-9a-f]*'), t_low REAL NOT NULL, t_high REAL NOT NULL, achieved_author REAL NOT NULL, achieved_distractor REAL NOT NULL, interval_low_lower REAL NOT NULL, interval_low_upper REAL NOT NULL, interval_high_lower REAL NOT NULL, interval_high_upper REAL NOT NULL, verdict TEXT NOT NULL CHECK(verdict IN ('separated','pair-incompatible')) CHECK((verdict='separated')=(t_low<t_high)) CHECK(interval_low_lower<=interval_low_upper) CHECK(interval_high_lower<=interval_high_upper));
CREATE TABLE eval_result (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, reference_id TEXT NOT NULL CHECK(length(reference_id)=64 AND reference_id NOT GLOB '*[^0-9a-f]*') REFERENCES reference(id) ON DELETE CASCADE, auc REAL NOT NULL, lower_bound REAL NOT NULL, cap REAL NOT NULL, author_segments INTEGER NOT NULL CHECK(author_segments>=0), distractor_segments INTEGER NOT NULL CHECK(distractor_segments>=0), author_clusters INTEGER NOT NULL CHECK(author_clusters>=0), distractor_clusters INTEGER NOT NULL CHECK(distractor_clusters>=0), discriminates INTEGER NOT NULL CHECK(discriminates IN (0,1)), calibrated INTEGER NOT NULL CHECK(calibrated IN (0,1)), shippable INTEGER NOT NULL CHECK(shippable IN (0,1)) CHECK(shippable=(discriminates AND calibrated)), reason TEXT NOT NULL CHECK(reason IN ('','discrimination-failed','uncalibrated')) CHECK((shippable=1)=(reason='')));
CREATE TABLE exemplar_selection (id TEXT NOT NULL PRIMARY KEY CHECK(length(id)=64 AND id NOT GLOB '*[^0-9a-f]*'), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, n INTEGER NOT NULL CHECK(n>=0), certificate_id TEXT NOT NULL CHECK(length(certificate_id)=64 AND certificate_id NOT GLOB '*[^0-9a-f]*'));
CREATE TABLE exemplar_member (selection_id TEXT NOT NULL CHECK(length(selection_id)=64 AND selection_id NOT GLOB '*[^0-9a-f]*') REFERENCES exemplar_selection(id) ON DELETE CASCADE, ordinal INTEGER NOT NULL CHECK(ordinal>=0), node_id TEXT NOT NULL CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*') REFERENCES node(node_id) ON DELETE CASCADE, PRIMARY KEY(selection_id,ordinal));
CREATE TABLE rewrite_attempt (invocation_id TEXT NOT NULL CHECK(length(invocation_id)=64 AND invocation_id NOT GLOB '*[^0-9a-f]*'), attempt_index INTEGER NOT NULL CHECK(attempt_index>=0), profile_id TEXT NOT NULL CHECK(length(profile_id)=64 AND profile_id NOT GLOB '*[^0-9a-f]*') REFERENCES profile(id) ON DELETE CASCADE, provider_id TEXT NOT NULL CHECK(provider_id IN ('ollama','anthropic')), node_id TEXT NOT NULL CHECK(length(node_id)=64 AND node_id NOT GLOB '*[^0-9a-f]*') REFERENCES node(node_id) ON DELETE CASCADE, current_hash TEXT NOT NULL CHECK(length(current_hash)=64 AND current_hash NOT GLOB '*[^0-9a-f]*'), candidate_hash TEXT NOT NULL CHECK(length(candidate_hash)=64 AND candidate_hash NOT GLOB '*[^0-9a-f]*'), current_distance REAL NOT NULL, candidate_distance REAL NOT NULL, current_band TEXT NOT NULL CHECK(current_band IN ('','in-range','drifting','not-you')), candidate_band TEXT NOT NULL CHECK(candidate_band IN ('','in-range','drifting','not-you')), preserved INTEGER NOT NULL CHECK(preserved IN (0,1)), tells_comparison INTEGER NOT NULL, tells_comparable INTEGER NOT NULL CHECK(tells_comparable IN (0,1)), accepted INTEGER NOT NULL CHECK(accepted IN (0,1)), rejection TEXT NOT NULL CHECK(rejection IN ('','not-one-segment','unscoreable','candidate-unscoreable','uncalibrated','different-features','not-preserved','tells-incomparable','tells-worse','not-improved')) CHECK((accepted=1)=(rejection='')) CHECK(accepted=0 OR (current_band<>'' AND candidate_band<>'')), PRIMARY KEY(invocation_id,attempt_index));
CREATE TABLE rewrite_attempt_identifier (invocation_id TEXT NOT NULL CHECK(length(invocation_id)=64 AND invocation_id NOT GLOB '*[^0-9a-f]*'), attempt_index INTEGER NOT NULL CHECK(attempt_index>=0), ordinal INTEGER NOT NULL CHECK(ordinal>=0), identifier TEXT NOT NULL CHECK(identifier GLOB 'preserve-v1:*:*:????????????????' AND identifier NOT GLOB '*[^a-z0-9:-]*'), PRIMARY KEY(invocation_id,attempt_index,ordinal), FOREIGN KEY(invocation_id,attempt_index) REFERENCES rewrite_attempt(invocation_id,attempt_index) ON DELETE CASCADE);
`}
